spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://194.32.248.42:5432/certbot
    username: postgres
    password: 2223404egor
    hikari:
      pool-name: fl-pool
      minimum-idle: 5
      idle-timeout: 0
      maximum-pool-size: 16
      connection-timeout: 5000
      max-lifetime: 600000
  jpa:
    database: POSTGRESQL
    show-sql: true
    generate-ddl: false
    hibernate:
      use-new-id-generator-mappings: true
      #ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        generate_statistics: true
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect

server:
  port: 5000


